#+TITLE: package: Emacs Package Manager
#+AUTHOR: Aqeel Akber

* package

The Emacs Package Manager, intialize and add the MELPA repository.

#+BEGIN_SRC emacs-lisp
  (require 'package)
  (let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                      (not (gnutls-available-p))))
         (url (concat (if no-ssl "http" "https") "://melpa.org/packages/")))
    (add-to-list 'package-archives (cons "melpa" url) t))
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
  (package-initialize)
#+END_SRC

* Base packages to install

This is where the magic happens. By adding package names to this list,
the package manager ensures that it is installed at startup when
running the next code block.

I only install base packages here, any plugins to these packages I
install when configuring that package. My configuration files have the
same name as the package name listed here. In the case where there is
crossover between the base packages via plugins I try to setup the
plugin in the configuration for its base package. For example,
=company-irony= is configured in [[company.org]].

#+BEGIN_SRC emacs-lisp
  (setq my-package-list '(base16-theme
                          company
                          company-irony
                          flycheck
                          flycheck-irony
                          helm
                          irony
                          yasnippet))
#+END_SRC

* Install base packages

This makes sure all the packages I want are installed when I start up
emacs.

#+BEGIN_SRC emacs-lisp
  (mapc #'package-install my-package-list)
#+END_SRC

