#+TITLE: simplemacs, nothing complex.
#+AUTHOR: Aqeel Akber <aqeel.akber@gmail.com>

* Introduction

Simplemacs is the configuration you give your keen newbie hacker friend
when introducing them the wonderful world of emacs.

Simplemacs is the configuration you use when you just want to GTD.

Ugh, yet another emacs configuration I hear you say, and yes I can't
deny that. Let me place this one relative to others with a table:

#+CAPTION: Where simplemacs sits relative to other emacs configurations
|       | Small / Simple      | Large / Complex        |
| Neat  | [[https://github.com/admiralakber/simplemacs][simplemacs]]          | [[https://github.com/xiaohanyu/oh-my-emacs][oh-my-emacs]], [[http://spacemacs.org/][spacemacs]] |
| Messy | old mate's dotfiles | [[https://www.emacswiki.org/emacs/DotEmacsBankruptcy][.emacs bankrupt]]        |

It's basically old mate's dotfiles, where old mate is obsessive about
neat code, loves =org-mode=, and minimalism. The entire repository
should be self documenting, and concise. Have a browse!

* Quick start

*Step zero*

Install [[https://www.gnu.org/software/emacs/][emacs]] version > 24.4

*Step one*

Back up your existing stuff and clone it in.

#+BEGIN_SRC bash
mv ~/.emacs.d ~/.emacs.d.bak
git clone https://github.com/admiralakber/simplemacs ~/.emacs.d
#+END_SRC

*Step two*

If you want to use =notmuch= in emacs, be sure to edit
[[file:modules/notmuch.org]] and uncomment the region in [[file:init.el]]

*Step three*

Run =emacs=. 

If it doesn't work, try run =M-x list-packages= to update the cache,
and open =emacs= again.

*(Optional) Step four*

Install the included helper script =emc= into your =$PATH=.

You can then call this to use emacs in client / daemon mode
transparently.

* The so called "modules"

Simplemacs makes no attempt to create a unified configuration wrapper
or anything like that. It's emacs configuration by the [[https://en.wikipedia.org/wiki/Unix_philosophy][UNIX
Philosophy]], find the appropriate file for the package and edit it
yourself.

| File                        | Requires | Notes                    |
| [[file:init.el]]                | None     | Start here               |
| [[file:modules/package.org]]    | None     | Package management       |
| [[file:modules/org.org]]        | None     | Beloved Org mode         |
| [[file:modules/aesthetics.org]] | None     | Theme to your taste here |
| [[file:modules/notmuch.org]]    | [[https://notmuchmail.org/][notmuch]]  | Email (edit me!)         |
| [[file:modules/helm.org]]       | None     | Minibuffer completion    |
| [[file:modules/company.org]]    | None     | Buffer completion        |
| [[file:modules/yasnippet.org]]  | None     | Quick templates          |
| [[file:modules/flyspell.org]]   | None     | Spell checking           |
| [[file:modules/flycheck.org]]   | None     | Syntax / Style checking  |

** The so called "activities"

I have extended the modules outline to include "activities". This is
for activity specific configuration. 

| File                                    | Requires | Notes       |
| [[file:modules/activities/programming.org]] | None     | Minor modes |

* Contributing ♥

Be kind. Make issues / forks. Pull requests encouraged, even if it's
just removing whitespaces or fixing grammar.


